apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscluster-e905"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscluster-e905"
  template:
    metadata:
      labels:
        app: "akscluster-e905"
    spec:
      containers:
        - name: "akscluster-e905"
          image: "demoaz204bern.azurecr.io/akscluster"
          ports:
          - containerPort: 80