apiVersion : apps/v1
kind: Deployment
metadata:
  name: "heroescluster-0403"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "heroescluster-0403"
  template:
    metadata:
      labels:
        app: "heroescluster-0403"
    spec:
      containers:
        - name: "heroescluster-0403"
          image: "heroes.azurecr.io/heroescluster"
          ports:
          - containerPort: 3000