apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscluster-f6b1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscluster-f6b1"
  template:
    metadata:
      labels:
        app: "akscluster-f6b1"
    spec:
      containers:
        - name: "akscluster-f6b1"
          image: "az104thomaszh.azurecr.io/akscluster"
          ports:
          - containerPort: 80