apiVersion: v1
kind: Service
metadata:
    name: "demoapp"
    labels:
        app: "demoapp"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "demoapp"