apiVersion: v1
kind: Service
metadata:
    name: "akscluster-1d84"
    labels:
        app: "akscluster-1d84"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akscluster-1d84"